// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyhXua-MVyOL-zpfW6Y3oTIkpGxdjyAAw',
    appId: '1:519110917048:web:6d683b42e65f91735bed4d',
    messagingSenderId: '519110917048',
    projectId: 'reshop-a42f1',
    authDomain: 'reshop-a42f1.firebaseapp.com',
    databaseURL: 'https://reshop-a42f1-default-rtdb.firebaseio.com',
    storageBucket: 'reshop-a42f1.appspot.com',
    measurementId: 'G-7Y4587H00N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6PUwz2SGMQXHbRsvZV5zTyiIssqKXEJI',
    appId: '1:519110917048:android:0097c99bb51f74935bed4d',
    messagingSenderId: '519110917048',
    projectId: 'reshop-a42f1',
    databaseURL: 'https://reshop-a42f1-default-rtdb.firebaseio.com',
    storageBucket: 'reshop-a42f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxHzOSSvU_khqoL5bXHPOfRf1xESS952Q',
    appId: '1:519110917048:ios:f656287c42f5171e5bed4d',
    messagingSenderId: '519110917048',
    projectId: 'reshop-a42f1',
    databaseURL: 'https://reshop-a42f1-default-rtdb.firebaseio.com',
    storageBucket: 'reshop-a42f1.appspot.com',
    androidClientId: '519110917048-eghjanpp1ao4hsf8emn59n5q6p8uil9s.apps.googleusercontent.com',
    iosClientId: '519110917048-kttd4clctl0k961qr6q4pa1l1g1vfbh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.responsivedashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxHzOSSvU_khqoL5bXHPOfRf1xESS952Q',
    appId: '1:519110917048:ios:f656287c42f5171e5bed4d',
    messagingSenderId: '519110917048',
    projectId: 'reshop-a42f1',
    databaseURL: 'https://reshop-a42f1-default-rtdb.firebaseio.com',
    storageBucket: 'reshop-a42f1.appspot.com',
    androidClientId: '519110917048-eghjanpp1ao4hsf8emn59n5q6p8uil9s.apps.googleusercontent.com',
    iosClientId: '519110917048-kttd4clctl0k961qr6q4pa1l1g1vfbh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.responsivedashboard',
  );
}
